
exports.seed = function(knex, Promise) {
      // Inserts seed entries
      return knex('authors').insert([
        {id: 1, name: 'Michelle Obama', description: 'Michelle LaVaughn Obama is an American lawyer, university administrator and writer, who was First Lady of the United States from 2009 to 2017. She is married to the 44th U.S. president, Barack Obama, and was the first African-American first lady.', biography: 'Michelle LaVaughn Obama is an American lawyer, university administrator and writer, who was First Lady of the United States from 2009 to 2017. She is married to the 44th U.S. president, Barack Obama, and was the first African-American first lady.'},
        {id: 2, name: 'Ernest Hemingway', description: 'Ernest Hemingway was an American journalist, novelist, short-story writer, and noted sportsman. Many of his works are considered classics of American literature. ' , biography:'Ernest Hemingway was an American journalist, novelist, short-story writer, and noted sportsman. Many of his works are considered classics of American literature. '},
        {id: 3, name: 'Tracy Chevalier', description: 'Tracy Chevalier is an American-British historical novelist. She has writ ten eight novels. She is best known for her second novel, Girl with a Pearl Earring, which was adapted as a 2003 film starring Scarlett Johansson and Colin Firth. ' , biography: 'Tracy Chevalier is an American-British historical novelist. She has written eight novels. She is best known for her second novel, Girl with a Pearl Earring, which was adapted as a 2003 film starring Scarlett Johansson and Colin Firth. '},
        {id: 4, name: 'George Friedman', description: 'George Friedman is a Hungarian-born U.S. geopolitical forecaster, and strategist on international affairs. He is the founder and chairman of Geopolitical Futures, an online publication that analyzes and forecasts the course of global events. ', biography: 'George Friedman is a Hungarian-born U.S. geopolitical forecaster, and strategist on international affairs. He is the founder and chairman of Geopolitical Futures, an online publication that analyzes and forecasts the course of global events. '},
        {id: 5, name: 'George Martin', description: 'George R. R. Martin is an American novelist and short story writer in the fantasy, horror, and science fiction genres, screenwriter, and television producer. He is best known for his series of epic fantasy novels, A Song of Ice and Fire, which was adapted into the HBO series Game of Thrones.' , biography:'George R. R. Martin is an American novelist and short story writer in the fantasy, horror, and science fiction genres, screenwriter, and television producer. He is best known for his series of epic fantasy novels, A Song of Ice and Fire, which was adapted into the HBO series Game of Thrones.'},
        {id: 6, name: 'Antonio Tabucchi', description: 'Antonio Tabucchi was an Italian writer and academic who taught Portuguese language and literature at the University of Siena, Italy. In later life he was mentioned as a contender for the Nobel Prize in Literature, a feat he never achieved.' , biography: 'Antonio Tabucchi was an Italian writer and academic who taught Portuguese language and literature at the University of Siena, Italy. In later life he was mentioned as a contender for the Nobel Prize in Literature, a feat he never achieved.'},
        {id: 7, name: 'Robert Kiyosaki', description: 'Robert Kiyosaki is an American businessman and author. Kiyosaki is the founder of Rich Global LLC and the Rich Dad Company, a private financial education company that provides personal finance and business education to people through books and videos.' , biography: 'Robert Kiyosaki is an American businessman and author. Kiyosaki is the founder of Rich Global LLC and the Rich Dad Company, a private financial education company that provides personal finance and business education to people through books and videos.'},
        {id: 8, name: 'Margaret Atwood', description: 'Margaret Atwood is a Canadian poet, novelist, literary critic, essayist, inventor, teacher, and environmental activist. Atwood is also the inventor and developer of the LongPen and associated technologies that facilitate the remote robotic writing of documents.' , biography: 'Margaret Atwood is a Canadian poet, novelist, literary critic, essayist, inventor, teacher, and environmental activist. Atwood is also the inventor and developer of the LongPen and associated technologies that facilitate the remote robotic writing of documents.'},
        {id: 9, name: 'Rachel Hollis', description: 'Rachel Hollis is an American author, motivational speaker and blogger. Her self-help book Girl, Wash Your Face—since its release in February 2018—has maintained a spot in the top 10 best-selling books in the country for seven months.' , biography: 'Rachel Hollis is an American author, motivational speaker and blogger. Her self-help book Girl, Wash Your Face—since its release in February 2018—has maintained a spot in the top 10 best-selling books in the country for seven months.'},
        {id: 10, name: 'Tara Westover', description: 'Tara Westover is an American memoirist, essayist and historian. Her memoir Educated debuted at #1 on the New York Times bestseller list and was a finalist for a number of national awards.', biography:'Tara Westover is an American memoirist, essayist and historian. Her memoir Educated debuted at #1 on the New York Times bestseller list and was a finalist for a number of national awards.'},
        {id: 11, name: 'Tim Marshall', description: 'Tim Marshall is a British journalist, author and broadcaster, known for his analysis of developments in foreign news and international diplomacy. Marshall is a guest commentator on world events for the BBC, Sky News and a guest presenter on LBC.' , biography: 'Tim Marshall is a British journalist, author and broadcaster, known for his analysis of developments in foreign news and international diplomacy. Marshall is a guest commentator on world events for the BBC, Sky News and a guest presenter on LBC.' },
        {id: 12, name: 'Cassandra Clare', description: 'Judith Lewis (née Rumelt, born July 27, 1973), better known by her pen name Cassandra Clare, is an American author of young adult fiction, best known for her bestselling series The Mortal Instruments', biography: 'Clare was born Judith Rumelt, to American parents, in Tehran, Iran. Her parents are Elizabeth and Richard Rumelt, who are a business school professor and author, respectively. Her maternal grandfather was film producer Max Rosenberg. Clare is Jewish, and has described her family as "not religious". As a child, Clare traveled frequently, spending time in Switzerland, England, and France. She returned to Los Angeles for high school, and from then on split her time between California and New York City, where she worked at various entertainment magazines and tabloids, including The Hollywood Reporter. While living in Los Angeles Clare began writing fan fiction using the name Cassandra Claire. The Draco Trilogy, based on Harry Potter and The Very Secret Diaries, based on The Lord of the Rings were popular. However, she deleted her fan fiction from the Internet shortly before her first novel, The City of Bones, was published under the name Cassandra Clare. She is also friends with author Holly Black, and their books occasionally overlap, Clare mentioning characters from Black\'s novels and vice versa, such as Val and Luis from Black\'s Valiant. Clare is also credited by her publisher with creating the "City of Fallen Angels treatment" where a tangible "letter" from one character to another is attached to the back of physical copies of a book. The goal is to spur print book sales. She currently resides in Amherst, Massachusetts, with her husband, Joshua Lewis, and three cats.'},
        {id: 13, name: 'Sarah Rees Brennan', description:'Sarah Rees Brennan (born 21 September 1983) is an Irish writer best known for young adult fantasy fiction. Her first novel, The Demon\'s Lexicon, was released June 2009 by Simon & Schuster. Brennan\'s books are bestsellers in the UK.', biography:'Brennan was born in Ireland. She lived in New York after college. She obtained a Creative Writing MA and worked as a librarian in Surrey, England, before moving to Dublin where she currently lives. Brennan has been writing since the age of five. She has a blog on Livejournal which has over 5000 subscribers. She wrote her first novel, The Demon\'s Lexicon, while studying for her Creative Writing MA. The publishing house Simon & Schuster obtained a three-book contract deal with her which involved an undisclosed six-figure sum. The series is YA fantasy, focusing on two brothers, Nick and Alan Ryves, and is set in the urban landscape - London and Exeter - of contemporary England.'},
        {id: 14, name: 'Maureen Johnson', description:'Maureen Johnson (born February 16, 1973) is an American author of young adult fiction. She has published thirteen young adult novels to date, including such series as the Truly Devious novels, the Shades of London series, and Suite Scarlett. Johnson\'s work has also appeared in numerous written anthologies, and comprises notable collaborative works with her contemporaries, such as Let It Snow, a holiday romance novel currently under adaption to film for distribution by Netflix.', biography:'Maureen Johnson is a graduate of the University of Delaware. Prior to that she attended an all-girl Catholic preparatory high school. In the short period between her undergraduate and graduate careers, Johnson worked in Philadelphia, London, and New York City. She was the literary manager of a Philadelphia theater company, a waitress in a theme restaurant, a secretary, a bartender in Piccadilly, and an occasional performer. She studied both writing and theatrical dramaturgy at Columbia University, where she received her MFA in Writing.'},
        {id: 15, name: 'Robin Wasserman', description:'Robin Wasserman (born May 31, 1978) is an American young adult novelist.', biography:'Wasserman grew up outside of Philadelphia and graduated from Harvard University and UCLA. Before she was an author she was an associate editor at a children\'s book publisher. She is currently living in Brooklyn, New York.'},
      ]);
};
